### ISSUE TITLE
页面空白

### ISSUE THREAD

**Issue by Aiba-Asagi** [yjl9903/Miki-Captain#17]
### Describe the bug

大佬您好，我按照您的提示部署后;
setting-pages-branch设置成了gh-pages-root;
css、js无法加载，就比如js文件请求路径是https://cube-yj.github.io/assets/index.09b3b149.js ;
想请教一下应该如何设置.

### Used Package Manager

None

**Comment by yjl9903** [comment]
如果你使用 GitHub Pages 部署的话，它会放到 `https://cube-yj.github.io/<your_repo_name>/` 下。

给 vite.config.ts 配一下 base，见 https://vitejs.dev/config/shared-options.html#base

或者 vite build 的时候，添加 `--base` 参数，例如 `vite build app --base /<your_repo_name>/`

https://github.com/yjl9903/Miki-Captain/blob/89c08dc9568faf71b2aa9e1443a94a10ccfb3233/package.json#L4

**Comment by yjl9903** [comment]
如果你愿意的话，我这里更推荐使用 netlify / vercel / cloudflare pages 等平台部署页面，没有这种问题。
