### ISSUE TITLE
在GitHubPage使用此模板部署项目后,子功能页面刷新后均会出现404

### ISSUE THREAD

**Issue by skyatgit** [yjl9903/Miki-Captain#19]
### Describe the bug

1.由于GitHubPage域名解析逻辑的问题，用户在访问/summary等子功能路径后刷新时会出现404，
将 app/src/router.ts 中的 history: createWebHistory(),改为createWebHashHistory可以解决此问题

2.同时经测试 https://github.com/yjl9903/Miki-Captain/issues/17 中提到的
vite build 的时候，添加 --base 参数，例如 vite build app --base /<your_repo_name>/
也无法完全修正显示问题

目前测试过最好的解决方法就是 不进行2中的改动,在GitHubPage通过CNAME的方式使用自定义域名，然后应用1中提到的改的，即可使网站在GitHubPage上正常显示
这里有一个修复过的项目可以看一下   https://github.com/Showeee/Captain

### Used Package Manager

None

**Comment by yjl9903** [comment]
1. 这个仓库没有用 github pages，你自己生成部署的时候可以自己修改一些配置。
2. 没记错的话，项目应该都是静态的，可以用 SSG 生成好所有页面，就没有你说的问题了。
